server:
    port: 8080
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/homestay?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: newpwd
      driver-class-name: com.mysql.jdbc.Driver
    mvc:
      view:
        prefix: /html/
        suffix: .html
    servlet:
      multipart:
        max-request-size: 10MB
        max-file-size: 10MB
mybatis:
    mapper-locations: classpath*:mapper/*.xml
    type-aliases-package: com.example.demo.entity
logging:
    level:
      org:
        springframework: debug
        mybatis: debug
        apache:
          ibatis: debug

